---
# tasks file for collectd
#
- name: Install collectd
  ansible.builtin.apt: 
    name: "{{ collectd_bin }}"
    state: present

- name: Deploy default configuration
  ansible.builtin.template:
    src: "{{ collectd_default_config }}"
    dest: /etc/collectd/collectd.conf
    owner: root
    group: root
  notify: restart collectd
  tags: [config]

- name: Deploy custom configuration
  ansible.builtin.copy:
    dest: /etc/collectd/collectd.conf.d/{{item.name}}.conf
    content: "{{ item.content }}"
    owner: root
    group: root
  with_items: collectd_config
  notify: restart collectd
  tags: [config]

- name: Start collectd
  ansible.builtin.service:
    name: collectd.service
    state: started
    enabled: true
